"""Single source of truth for the version the built apps report.

Both specs read vtc/__init__.py through here rather than repeating the number,
because repeating it drifted: the shipped v1.2 .app still told Finder it was
1.0.1, and the Windows .exe went on telling Explorer 1.2 after that was fixed —
its version resource was a hand-maintained file nothing regenerated.

Kept dependency-free and importable outside PyInstaller so it can be tested.
"""
from __future__ import annotations

import os
import re

_LEADING_NUMBERS = re.compile(r"^\d+(?:\.\d+)*")


def read_version(repo_root: str) -> str:
    """`__version__` out of vtc/__init__.py, e.g. '1.4.0' (or '1.4.0b1')."""
    init = os.path.join(repo_root, "vtc", "__init__.py")
    with open(init, encoding="utf-8") as fh:
        m = re.search(r'^__version__\s*=\s*["\']([^"\']+)["\']', fh.read(), re.M)
    if not m:
        raise SystemExit(f"could not read __version__ from {init}")
    return m.group(1)


def numeric_version(version: str) -> str:
    """The dotted-integer prefix of a version — '1.4.0b1' -> '1.4.0'.

    Both platforms' metadata reject a version with a suffix on it: an Info.plist
    CFBundleShortVersionString must be one to three integers, and a Windows
    VSVersionInfo takes four. A pre-release tag would produce an invalid bundle,
    so strip it rather than ship one.
    """
    m = _LEADING_NUMBERS.match(version.strip())
    return m.group(0) if m else "0"


def version_tuple(version: str) -> tuple[int, int, int, int]:
    """Four ints for a Windows VSVersionInfo — '1.4' -> (1, 4, 0, 0)."""
    parts = [int(p) for p in numeric_version(version).split(".")[:4]]
    return tuple(parts + [0] * (4 - len(parts)))  # type: ignore[return-value]


def win_version_resource(version: str) -> str:
    """The PyInstaller Windows version resource, generated from `version`."""
    vt = version_tuple(version)
    num = numeric_version(version)
    return f"""# GENERATED by packaging/appversion.py — do not edit, edit vtc/__init__.py.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={vt},
    prodvers={vt},
    mask=0x3f, flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0, date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      StringTable('040904B0', [
        StringStruct('CompanyName', 'Picnic Labs'),
        StringStruct('FileDescription', 'Very Thoughtful Compression'),
        StringStruct('FileVersion', '{num}'),
        StringStruct('InternalName', 'VeryThoughtfulCompression'),
        StringStruct('OriginalFilename', 'VeryThoughtfulCompression.exe'),
        StringStruct('ProductName', 'Very Thoughtful Compression'),
        StringStruct('ProductVersion', '{num}'),
      ]),
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])]),
  ],
)
"""


def write_win_version_resource(version: str, out_dir: str) -> str:
    """Write the resource into `out_dir` and return its path."""
    os.makedirs(out_dir, exist_ok=True)
    path = os.path.join(out_dir, "version_win.txt")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(win_version_resource(version))
    return path
